include: package:flutter_lints/flutter.yaml

analyzer:
  errors:

linter:
  rules:
    avoid_print: true
    prefer_const_constructors_in_immutables: false
    constant_identifier_names: false
    file_names: false
    prefer_function_declarations_over_variables: false
    prefer_const_constructors: false # 나중에 릴리즈 할때 이 옵션 해제해서 한번에 처리
    prefer_const_literals_to_create_immutables: false # 나중에 릴리즈 할때 이 옵션 해제해서 한번에 처리